Repository insberr/schedule-personalizer, pull requests merged in 2022-10, with the labels that each got.

#73 Create custom classes, need to make overrides work
  src/config/events.ts
  src/config/lunches.ts
  src/config/schedules.ts
  src/config/settings.ts
  src/pages/schedule/cambridge.ts
  src/pages/schedule/handleOverides.ts
  src/pages/schedule/index.tsx
  src/storage/store.ts
  src/storage/studentvueData.ts
  src/types.ts
  src/types/lunchesTypes.ts
Labels: todo, do soon

#86 Jake
  .eslintrc.json
  .gitignore
  Jakefile
  package.json
  src/index.html
  src/legal.mdx
  src/splashscreens/apple-splash-1125-2436.png
  src/splashscreens/apple-splash-1136-640.png
  src/splashscreens/apple-splash-1170-2532.png
  src/splashscreens/apple-splash-1179-2556.png
  src/splashscreens/apple-splash-1242-2208.png
  src/splashscreens/apple-splash-1242-2688.png
  src/splashscreens/apple-splash-1284-2778.png
  src/splashscreens/apple-splash-1290-2796.png
  src/splashscreens/apple-splash-1334-750.png
  src/splashscreens/apple-splash-1536-2048.png
  src/splashscreens/apple-splash-1620-2160.png
  src/splashscreens/apple-splash-1668-2224.png
  src/splashscreens/apple-splash-1668-2388.png
  src/splashscreens/apple-splash-1792-828.png
  src/splashscreens/apple-splash-2048-1536.png
  src/splashscreens/apple-splash-2048-2732.png
  src/splashscreens/apple-splash-2160-1620.png
  src/splashscreens/apple-splash-2208-1242.png
  src/splashscreens/apple-splash-2224-1668.png
  src/splashscreens/apple-splash-2388-1668.png
  src/splashscreens/apple-splash-2436-1125.png
  src/splashscreens/apple-splash-2532-1170.png
  src/splashscreens/apple-splash-2556-1179.png
  src/splashscreens/apple-splash-2688-1242.png
  src/splashscreens/apple-splash-2732-2048.png
  src/splashscreens/apple-splash-2778-1284.png
  src/splashscreens/apple-splash-2796-1290.png
  src/splashscreens/apple-splash-640-1136.png
  src/splashscreens/apple-splash-750-1334.png
  src/splashscreens/apple-splash-828-1792.png
  yarn.lock
Labels: internal

#91 Logout login/logout button
  readme.md
  src/App.tsx
  src/components/StudentVueReloader.tsx
  src/index.html
  src/index.tsx
  src/pages/login/Login.tsx
  src/pages/schedule/components/Timer.tsx
  src/pages/schedule/index.tsx
  src/pages/settings/index.tsx
  src/static/404.html
  src/storage/page.ts
Labels: enhancement, style, internal
